export const TRACKED_STOCKS = [
  // Current list kept from your project
  { ticker: "NVDA", name: "NVIDIA", sector: "Semiconductors / AI", enabled: true },
  { ticker: "AAPL", name: "Apple", sector: "Technology", enabled: true },
  { ticker: "MSFT", name: "Microsoft", sector: "Technology", enabled: true },
  { ticker: "TSLA", name: "Tesla", sector: "Automotive / EV", enabled: true },
  { ticker: "AMZN", name: "Amazon", sector: "Ecommerce / Cloud", enabled: true },
  { ticker: "GOOGL", name: "Alphabet Class A", sector: "Technology", enabled: true },
  { ticker: "META", name: "Meta Platforms", sector: "Technology", enabled: true },
  { ticker: "JPM", name: "JPMorgan Chase", sector: "Financials", enabled: true },
  { ticker: "AMD", name: "Advanced Micro Devices", sector: "Semiconductors", enabled: true },
  { ticker: "NFLX", name: "Netflix", sector: "Streaming", enabled: true },
  { ticker: "SPY", name: "SPDR S&P 500 ETF", sector: "ETF", enabled: true },
  { ticker: "QQQ", name: "Invesco QQQ ETF", sector: "ETF", enabled: true },
  { ticker: "LHX", name: "L3Harris Technologies", sector: "Defense", enabled: true },
  { ticker: "IRDM", name: "Iridium Communications", sector: "Satellite", enabled: true },
  { ticker: "BA", name: "Boeing", sector: "Aerospace", enabled: true },
  { ticker: "GE", name: "GE Aerospace", sector: "Industrial", enabled: true },
  { ticker: "NOC", name: "Northrop Grumman", sector: "Defense", enabled: true },
  { ticker: "QQQM", name: "Invesco NASDAQ 100 ETF", sector: "ETF", enabled: true },

  // Added large, liquid S&P 500 names for a 30-symbol watchlist
  { ticker: "AVGO", name: "Broadcom", sector: "Semiconductors", enabled: true },
  { ticker: "V", name: "Visa", sector: "Payments", enabled: true },
  { ticker: "MA", name: "Mastercard", sector: "Payments", enabled: true },
  { ticker: "COST", name: "Costco", sector: "Consumer Staples", enabled: true },
  { ticker: "WMT", name: "Walmart", sector: "Consumer Staples", enabled: true },
  { ticker: "XOM", name: "Exxon Mobil", sector: "Energy", enabled: true },
  { ticker: "LLY", name: "Eli Lilly", sector: "Healthcare", enabled: true },
  { ticker: "UNH", name: "UnitedHealth Group", sector: "Healthcare", enabled: true },
  { ticker: "HD", name: "Home Depot", sector: "Consumer Discretionary", enabled: true },
  { ticker: "PG", name: "Procter & Gamble", sector: "Consumer Staples", enabled: true },
  { ticker: "ORCL", name: "Oracle", sector: "Cloud Software", enabled: true },
  { ticker: "CRM", name: "Salesforce", sector: "Cloud Software", enabled: true },
];
